<div class="container a_propos">
    <h3>Conditions générales de ventes</h3>
    <h4>ACCUEIL » CONDITIONS GÉNÉRALES DE VENTES</h4>

    <article></article>
        <h4>Article 1 : Objet</h4>
        <p> 
            La société ptit dej (ci-après dénommée « Mon Ptit dej' »), société au capital de 3.000 euros, inscrite au RCS de Versailles sous le numéro XXX XXX XXX et dont le siège est situé au 19 rue Ptit Dej, 75015 Paris, propose principalement la vente de petits dejeuner (ci-après les « Produits ») via son site Internet monptitdej.fr . Les présentes Conditions Générales de Vente ont pour objet de définir les droits et obligations de Mon ptit dej' et de toute personne visitant ou effectuant un achat sur le Site Internet (ci-après dénommé le « Client »).
        </p>
        <p>Mon Ptit dej' et ses Clients sont ci-après dénommés ensemble les « Parties ».</p>
        
    <article></article>
    <h4>Article 2 : Application</h4>
    <p>
        Les présentes Conditions Générales de Vente s’appliquent, sans restriction ni réserve, à l’ensemble des ventes des Produits proposés par Mon Ptit dej' sur son Site Internet. Elles prévalent dans tous les cas sur tout autre document émis qui n’ont qu’une valeur indicative (tels que renseignements fournis de façon directe ou publicitaire sur les produits, etc.)
    </p>
    <p>
Toute commande passée sur le Site Internet suppose l’acceptation des présentes Conditions Générales, dont le client reconnaît avoir pris connaissance, les avoir comprises et acceptées en parfaite connaissance de cause. Toute condition contraire opposée par le Client est inopposable, à défaut d’acceptation expresse de Mon Ptit dej'.
</p>

 <p>
 En acceptant les présentes Conditions Générales, le Client déclare par ailleurs être majeur et pleinement capable de contracter.
 </p>

<p>
Le Client peut, à tout moment, prendre connaissance des présentes Conditions Générales de Vente sur le Site Internet monptitdej'.fr. Le Client dispose de la faculté de sauvegarde ou d’édition des présentes Conditions Générales. Les présentes Conditions Générales sont soumises à la loi française et aux normes françaises en vigueur.
</p>

<p>Mon Ptit dej' se réserve le droit de modifier les présentes Conditions Générales de Vente à tout moment, sans préavis, étant entendu que de telles modifications seront inapplicables aux réservations et aux commandes préalablement acceptées et confirmées par le Client.</p>
    <article></article>
    <h4>Article 3 : Commande</h4>
<p>La prise de commande suppose l’inscription préalable du Client sur le Site Internet en vue de la création d’un compte Client.</p>
<p>
Lors de cette inscription, le Client doit renseigner au minimum :
<ul>
    <li>
Son prénom
    </li>
    <li>Son nom</li>
    <li>Une adresse de courrier électronique valide</li>
    <li>Un mot de passe</li>
</ul>
</p>
 <p>Il appartient au Client de garder ces informations strictement confidentielles et de ne pas les communiquer à des tiers, afin d’éviter autant que possible tout risque d’intrusion dans son compte client.
</p>

<p>L’accès au compte client s’effectue sous le seul contrôle du Client et sous sa responsabilité.</p>

<p>Mon Ptit dej' ne saurait être responsable de toute utilisation du compte client par un tiers qui aurait eu accès à son identifiant et à son mot de passe, que ce soit à l’initiative du Client ou par sa négligence.</p>

<p>Lorsque le Client confirme sa commande en cliquant sur l’icône « Procéder au paiement » (ci-après et ci-avant « la Commande »), il est considéré comme ayant accepté en connaissance de cause le contenu et les conditions de la Commande en cause et en particulier les présentes Conditions Générales de Vente, les prix, caractéristiques, quantités et délais de livraison des produits proposés à la vente et commandés par le Client.</p>
​
<p>Mon Ptit dej' confirmera ensuite cette commande par l’envoi d’un courrier électronique au client.</p>
<p>En outre, Mon Ptit dej' se réserve le droit de suspendre ou d’annuler toute exécution d’une Commande et/ou livraison, quelle que soit sa nature et niveau d’exécution, en cas de défaut de paiement ou paiement partiel de toute somme qui serait due, en cas d’incident de paiement, ou en cas de fraude ou tentative de fraude relative à l’utilisation du Site Internet, y compris à l’occasion de commandes antérieures.
</p>
​
<p>En cas d’erreur de saisie de l’adresse de messagerie électronique concernée, ou de non réception du message électronique de confirmation de commande, la responsabilité de Mon Ptit dej' ne saurait être engagée. Dans ce cas la vente sera considérée comme définitive, hors les cas d’annulation de la commande par Mon Ptit dej', notamment pour indisponibilité des produits (comme prévu à l’article 6).</p>

<p>Mon Ptit dej' se réserve également le droit d’annuler une commande ou de la suspendre pour des motifs internes (rupture de stocks, perturbation du service logistique, etc.), le Client sera remboursé des frais engagés par ses soins sur cette commande mais ne pourra prétendre à aucune indemnisation.
</p>
<p>En plus de ses informations d’identification, le Client doit fournir une adresse de livraison et un numéro de téléphone pour valider l’enregistrement de la Commande. Le Client est entièrement responsable des informations saisies dans le bon de commande. Ces informations conservées dans le système d’information de Mon Ptit dej' ont force probante quant aux commandes passées. La responsabilité de Mon Ptit dej' ne saurait être recherchée ni engagée dans le cas où Mon Ptit dej' serait dans l’impossibilité de livrer ou d’exécuter la commande en raison d’erreurs, imprécisions ou omissions relativement à ces informations.
</p>
<p>Mon Ptit dej' se réserve le droit de refuser une commande si elle considère que la prestation ne pourra être délivrée dans des conditions satisfaisant ses standards.</p>
<p>Les commandes passées sur le site sont destinées à un usage personnel. Le Client s’interdit notamment de revendre les Produits à un tiers.</p>
    <article></article>
    ​<h4>Article 4 : Droit de rétractation</h4>

    <p>En vertu de l’Article L121-21-8 du Code de la Consommation, le droit de rétractation visé par l’article Article L121-21 du Code de la Consommation ne peut être exercé pour les contrats de fourniture de biens susceptibles de se détériorer ou de se périmer rapidement.</p>

    <p>Les produits vendus par Mon Ptit dej' étant périssables, ils ne sont donc ni repris, ni échangés.</p>
    <article></article>
    <h4>Article 5 : Produits</h4>
    <p>Le Site Internet présente les Produits à vendre ainsi que leurs descriptifs détaillés incluant les ingrédients des recettes. Conformément à la loi en vigueur, le consommateur a la possibilité de connaître avant la prise de commande définitive les caractéristiques essentielles des Produits qu’il souhaite acheter. Mon Ptit dej' se réserve le droit de modifier à tout moment le contenu de ses plats et d’en avertir le Client par la mise à jour de l’onglet « Ingrédients ».</p>

<p>Il appartient au Client de se renseigner sur ses allergies ou intolérance à certains produits et à rechercher les traces de ces produits dans l’onglet « Ingrédients ». Mon Ptit dej' ne pourra être tenu responsable des conséquences de la non prise en compte de ces informations par le Client lors de son achat.</p>


<p>Les photographies, graphismes et les descriptions des Produits proposés sur le Site Internet n’ont qu’une valeur indicative et ne rentrent pas dans le champ contractuel. Par ailleurs, des indications relatives au poids des plats pourront parfois être communiquées sur le site, et ce également à titre indicatif.</p>

<p>Les Produits sont conformes à la législation française en vigueur.</p>

<p>Mon Ptit dej' se réserve l’entière liberté de modifier, à tout moment, l’offre proposée sur le Site Internet, sans en informer au préalable le client, sans préjudice des commandes passées par le Client.</p>
    <article></article>
    <h4>Article 6 : Disponibilité des Produits</h4>

<p>Mon Ptit dej' propose sur son Site Internet des Produits qui sont en grande partie composés d’ingrédients frais. De ce fait, les Produits commandés par le Client pourraient ne plus être disponibles le jour prévu de la livraison ou du retrait en boutique en raison d’aléas climatiques, de l’indisponibilité des produits chez les fournisseurs ou toute autre raison. Dans un tel cas, Mon Ptit dej' s’engage à tenir le Client informé dans les plus brefs délais par courrier électronique ou par téléphone et à lui proposer une solution de remplacement ou un remboursement de sa commande.
</p>
<p>Aucune pénalité d’annulation ne sera appliquée en cas d’annulation de la commande pour indisponibilité. En cas de remplacement par une nouvelle commande, une validation formelle sera demandée au Client.
</p>
    <article></article>
    <h4>Article 7 : Tarifs</h4>


<p>Les prix de vente des Produits proposés sur le Site Internet sont ceux en vigueur, c’est-à-dire ceux affichés sur le Site Internet lors de l’enregistrement de la commande. Ils sont indiqués en euros toutes taxes comprises (TTC). Les prix sont soumis à la T.V.A. française applicable au jour du paiement, soit 5,5%, 10% ou 20% selon les catégories de produit. Tout changement du taux légal de cette T.V.A sera répercuté sur le prix des Produits présentés sur le Site Internet, à la date stipulée par le décret d’application s’y référant.</p>

<p>Les prix de vente des Produits peuvent être modifiés par Mon Ptit dej' à tout moment, le client se verra facturer au prix applicable lors de sa commande et déclare avoir pris connaissance du prix mentionné dans son panier et en accepter la charge avant de le valider.
</p>
<p>Les prix de vente ne comprennent pas les frais d’expédition, facturés en supplément du prix des Produits achetés suivant le montant de la commande. Les frais d’expédition seront indiqués avant l’enregistrement de la commande par le Client sous le terme “frais de livraison”.
</p>
    <article></article>
    <h4>Article 8 : Offres promotionnelles</h4>

<p>Mon Ptit dej' peut être amené à mettre en place des offres promotionnelles dans le cadre du développement de son activité. Ces offres peuvent être spécifiques et le Client doit en remplir les conditions pour en profiter.</p>

<p>Mon Ptit dej' se réserve de refuser à un Client l’utilisation d’un code promotionnel, d’une réduction ou d’un parrainage si elle en estime l’utilisation abusive. Dans ce cas, Mon Ptit dej' annulera la commande et procédera éventuellement au remboursement du montant initialement versé.</p>

<p>Par ailleurs, Mon Ptit dej' n’accepte qu’un seul compte par foyer. Les offres et autres promotions sont strictement limitées à un par foyer (même adresse de livraison ou numéro de téléphone), sauf accord explicite de Mon Ptit dej'.
</p>
    <article></article>
    <h4>Article 9 : Paiement</h4>

<p>Toutes les commandes sont payables en euros et le moyen de paiement accepté est la carte de paiement bancaire. Les règlements sont encaissés dès la réception et la validation de la commande par le Client. Pour tout autre moyen de paiement, le Client peut contacter Mon Ptit dej' par téléphone ou par mail.</p>

<p>Le Client garantit qu’il est pleinement autorisé à utiliser la carte de paiement pour le paiement de sa commande et que ces moyens de paiement donnent légalement accès à des fonds suffisants pour couvrir tous les coûts résultant de sa commande sur le Site Internet. Mon Ptit dej' ne pourra être tenu pour responsable de tout usage frauduleux du moyen de paiement utilisé.
</p>
<p>Les paiements par carte bancaire sont effectués par le biais du système sécurisé Stripe qui utilise le protocole TLS (Transport Layer Security) de telle sorte que les informations transmises sont cryptées par un logiciel et qu’aucun tiers ne peut en prendre connaissance au cours du transport sur le réseau.</p>
<p>Si le Client le souhaite, les coordonnées restent enregistrées pour que le Client n’ait pas à communiquer ces informations lors de chaque nouvelle commande. Le montant de chaque nouvelle commande sera débité automatiquement sur sa carte.</p>

​
<p>Mon Ptit dej' se réserve le droit de suspendre ou d’annuler toute commande et/ou livraison, quelle que soit sa nature et niveau d’exécution, en cas de non-paiement de toute somme qui serait due par le client ou en cas d’incident de paiement.</p>
<p>Des pénalités d’un montant égal au taux d’intérêt légal majoré de cinq points sont applicables de plein droit aux montants impayés à l’issue d’un délai de dix jours suivant la date de paiement supposé ou dès notification du rejet de paiement bancaire pour tout autre moyen de paiement.
</p>

<p>La livraison de toute nouvelle commande pourra être suspendue en cas de défaut de paiement d’une précédente commande et ce nonobstant les dispositions des présentes.</p>

<p>Il appartient au client d’enregistrer et d’imprimer son certificat de paiement s’il souhaite conserver les détails bancaires relatifs à sa transaction.</p>
    <article></article>
    <h4>Article 10 : Livraison</h4>
<p>
La livraison des produits proposés sur le Site Internet est proposée uniquement dans la zone de livraison indiquée sur le Site Internet qui est mise à jour régulièrement. Il n’est pas possible de passer commande hors de ladite zone de livraison. Si une commande était malencontreusement validée par le Site Internet tout en ne correspondant pas à la zone de livraison, Mon Ptit dej' se réserve le droit d’annuler et de rembourser la commande.
</p>
<p>Pour des raisons opérationnelles, la livraison s’effectue seulement à certains horaires, qui peuvent différer selon le lieu de livraison et indiqués au Client sur le Site Internet. Si une commande était malencontreusement validée sur le Site tout en ne correspondant pas aux horaires / règles de commande affichés sur le Site, Mon Ptit dej' se réserve le droit d’annuler et de rembourser la commande.
</p>​
<p>Le Client s’engage à être disponible pour réceptionner les produits à l’adresse et au créneau horaire qu’il a indiqué dans sa commande. La livraison est effectuée par une société prestataire de livraison à l’adresse indiquée par le Client au moment de sa commande. Le Client accepte que Mon Ptit dej' communique ses données personnelles nécessaire à la livraison (nom, prénom, adresse, numéro de téléphone, etc.) à ses partenaires prestataires de livraison.
</p>
<p>Au cas où l’adresse renseignée serait inexacte occasionnant un retard ou une non livraison, ni le prestataire pour la livraison, ni Mon Ptit dej' ne pourront être tenus pour responsables. La commande sera annulée et le montant de la commande ne pourra faire l’objet d’aucun dédommagement ni remboursement. Si le Client souhaite à nouveau se faire livrer, les potentiels frais additionnels de livraison seront à sa charge.
</p>

<p>De même, Mon Ptit dej' ne pourra pas être tenu pour responsable pour le retard ou la non livraison de la commande si l’accès au lieu de livraison est impossible au livreur (barrière, porte close, …).</p>
<p>Mon Ptit dej' communique sur différentes tranches horaires de livraison sur le Site Internet. Ces délais sont des délais indicatifs et des événements imprévisibles peuvent amener à des livraisons en avance ou en retard. Ainsi, un dépassement du délai de livraison avant ou après le créneau de livraison prévu ne sera être opposable à Mon Ptit dej' et le Client ne pourra réclamer ni remboursement ni indemnité ni toute autre forme de dédommagement.
</p>
<p>Mon Ptit dej' rejette toute responsabilité en cas de retard imputable à son prestataire externe de livraison.</p>​
<p>Il appartiendra au Client de vérifier les produits reçus au moment de leur livraison. En cas de produits manquants ou abîmés, le client devra envoyer ses constatations le jour de la réception au Service Client Mon Ptit dej'. Mon Ptit dej' s’engage à rembourser le montant des produits non-livrés si l’erreur est imputable à Mon Ptit dej'.
</p>
<p>Pour livrer en frais avec des tarifs attractifs, Mon Ptit dej' livre ses plats cuisinés frais dans un packaging innovant qui conserve les plats entre 0 et 4°C jusqu’à 48 heures. Lorsqu’il passe commande, le Client s’engage à récupérer le colis dans les 48 heures selon le mode de livraison qu’il aura choisi. Si le Client n’est pas chez lui au moment prévu pour la livraison et/ou ne va pas chercher son colis dans les 48 heures après son départ des locaux de Mon Ptit dej', Mon Ptit dej' n’est plus responsable du respect de la chaîne du froid. Le Client est alors entièrement responsable de la dégradation des plats et ne pourra demander de dédommagement.
</p>
    <article></article>
    <h4>Article 11 : Conservation des Produits</h4>
    <p>Le Client devra consommer les produits contenus dans sa commande avant la Date Limite de Consommation indiquée sur chaque produit. La responsabilité de Mon Ptit dej' ne pourra être engagée concernant la qualité des produits une fois ce délai passé.</p>
    <p>Mon Ptit dej' livre l’intégralité de ses produits froids et s’engage à en assurer la bonne conservation lors du transport de la marchandise. Le Client s’engage après livraison à assurer la bonne conservation de ses produits (au frais entre 0 et 4°C) et à les consommer avant la date indiquée sur l’emballage.</p>
    <p>Mon Ptit dej' ne pourra être tenu responsable de la détérioration des produits due à la négligence du Client et/ou la mauvaise conservation des produits après leur livraison.</p>
    <p>La détérioration des produits due au non-respect des indications de réchauffage mentionnées sur l’emballage ou à défaut sur le Site Internet ne pourra engager la responsabilité de Mon Ptit dej'.</p>
    <article></article>
    <h4>Article 12 : Accessibilité du Site Internet</h4>
<p>Le Site Internet est accessible par le Client 24 heures sur 24, 7 jours sur 7, sauf opération de maintenance programmée ou pour toute autre raison exceptionnelle.</p>
<p>Mon Ptit dej' ne saurait être tenue responsable en cas d’interruption temporaire ou définitive qui n’est pas de son fait et qui est imputable soit au Client, soit au fait imprévisible et insurmontable d’un tiers, soit à un cas de force majeure. Etant par son activité tenue à une obligation de moyen, la société Mon Ptit dej' ne pourra être tenue responsable de tout préjudice physique, matériel ou moral causé par l’indisponibilité du Site Internet.</p>
    <article></article>
    <h4>Article 13 : Contact</h4>
<p>Pour toute information, question, suivi de commande ou aide dans le choix des Produits proposés sur le Site Internet, le service client de Mon Ptit dej' est à votre disposition par courriel ou via l’onglet du Site Internet « Nous contacter » :
</p>
<p>Par courriel : contact@monptitdej'.fr</p>
    <article></article>
    <h4>Article 14 : Réserve de propriété</h4>
<p>Mon Ptit dej' se réserve la propriété pleine et entière des produits vendus jusqu’au parfait encaissement du prix facturé.</p>
    <article></article>
    <h4>Article 15 : Gestion des données personnelles</h4>
<p>L’inscription au site Mon Ptit dej' implique l’acceptation des présentes Conditions Générales de Vente. Les informations et données collectées par Mon Ptit dej' lors de l’inscription au Site ou lors d’une commande réalisée par le Client sont nécessaires aux relations commerciales, à la gestion des commandes et à la facturation.</p>

<p>Ces données peuvent être transmises aux sociétés qui contribuent à ces relations telles que celles chargées de l’exécution des services et commandes pour leur gestion, exécution, livraison, traitement et paiement (notamment aux livreurs). Ces informations et données sont également conservées à des fins de sécurité, afin de respecter les obligations légales et réglementaires, ainsi que pour permettre à Mon Ptit dej' d’améliorer et de personnaliser les services proposés et les informations adressées.</p>

<p>Conformément à la loi informatique et libertés, le Client dispose d’un droit d’accès et de rectification aux données personnelles qui les concernent. Le client devra écrire au Service Client de Mon Ptit dej' pour en faire la demande et joindre un justificatif d’identité.
</p>

<p>Mon Ptit dej' ne pourra être tenu pour responsable de la gestion non conforme des données personnelles par des tiers.</p>
</div>