<div class="container a_propos">
    <article>
        <h4>Mentions légales</h4>
        <p>
            Mon p'tit dej<br>
            7 rue du dejeuner<br>
            75013 Paris<br>
        </p>
        <p>
            Siret : 50156350600028<br>
            RCS : Paris B 501 563 506<br>
            Directeur de publication : BARSALI Boumediene<br>
        </p>
    </article>

    <article>
        <h4>Hébergement</h4>
        <p>
            OVH<br>
            RCS Roubaix – Tourcoing 424 761 419 00045<br>
            Code APE 6202A<br>
            N° TVA : FR 22 424 761 419<br>
        </p>
        <p>
            2 rue Kellermann<br>
            59100 Roubaix – France<br>
        </p>
    </article>

</div>