<h2>nouveau menu</h2>
<div class="back">
    <a href="<?=$router->generateUrl('dej_menus_show')?>" ><i class="fas fa-undo"></i>Revenir</a>
</div>
<form action="" method="POST" class="container" enctype = "multipart/form-data">
    <div class="row">
        <div class="col-10">
            <label for="name" >Nom :</label>
            <input type="text" name="name" id="name" >
        </div>
        <div class="col-10">
            <label for="nbrBoisson" >Combien de boissons chaudes (thé ou café):</label>
            <select name="nbrBoisson" >
                <?php for($i=0; $i<7;$i++):?>
                    <option value="<?=$i?>"><?=$i?></option>                                        
                <?php endfor;?>
            </select>
            <select name="boissonChaude" id="boissonChaude" class="col-6">
                <?php foreach($allBoissonsChaudes as $boissonChaude):?>
                    <option value="<?=$boissonChaude['id']?>"><?=$boissonChaude['name']?></option>
                <?php endforeach;?>
            </select>
        </div>
        <div class="col-10">
            <label for="viennoiseries" >Choississez vos viennoiseries :</label>
            <select name="nbrViennoiseries" >
                <?php for($i=0; $i<7;$i++):?>
                    <option value="<?=$i?>"><?=$i?></option>                                        
                <?php endfor;?>
            </select>
            <select name="viennoiseries" id="viennoiseries" class="col-6">
                <?php foreach($allViennoiseries as $viennoiseries):?>
                    <option value="<?=$viennoiseries['id']?>"><?=$viennoiseries['name']?></option>
                <?php endforeach;?>
            </select>
        </div>
        <div class="col-10">
            <label for="viennoiseries2" >Choississez vos viennoiseries :</label>
            <select name="nbrViennoiseries2" >
                <?php for($i=0; $i<7;$i++):?>
                    <option value="<?=$i?>"><?=$i?></option>                                        
                <?php endfor;?>
            </select>
            <select name="viennoiseries2" id="viennoiseries2" class="col-6">
                <?php foreach($allViennoiseries as $viennoiseries):?>
                    <option value="<?=$viennoiseries['id']?>" <?php if($viennoiseries['id'] != $allViennoiseries[0]['id']):?>selected<?php endif;?>><?=$viennoiseries['name']?></option>
                <?php endforeach;?>
            </select>
        </div>
        <div class="col-10">
            <label for="jus" >Choississez vos boissons :</label>
            <select name="nbrJus" >
                <?php for($i=0; $i<7;$i++):?>
                    <option value="<?=$i?>"><?=$i?></option>                                        
                <?php endfor;?>
            </select>
            <select name="jus" id="jus" class="col-6">
                <?php foreach($allJus as $jus):?>
                    <option value="<?=$jus['id']?>"><?=$jus['name']?></option>
                <?php endforeach;?>
            </select>
        </div>
        <div class="col-10">
            <label for="price">Prix :</label>
            <input type="text" name="price" id="price" >
        </div>
        <div class="col-10">
            <label for="img">Choissisez une image :</label>
            <input type="file" name="img" id="img" >
        </div>
        <div class="col-12 buttonDiv" >
            <button class="button1" type="submit">Envoyer</button>
        </div>
    </div>
</form>
