<div id="confirm">
    <h2>Cofirmation de votre commande</h2>
    <div class="container">
        <h4>Merci de votre commande </h4>
        <p>Vous avez choisi une livraison pour le  <strong><?=date_format(new DateTime($deliveryDate), 'd/m/Y')?> à <?=date_format(new DateTime($deliveryDate), 'H')?> h <?=date_format(new DateTime($deliveryDate), 'i')?></strong></p>
        <p>Retrouvez le detail de vos commandes dans votre compte.</p>
    </div>
</div>
