<div class="bigPhoto">
    <img src="<?=$router->getWwwPath()."/images/paris2.jpg"?>" alt="carte">
    <p class="paraPhoto">Nous livrons Paris 7 jours / 7</p>
</div>
<div  id="delivery" class="container-fluid">
    <p >Nous vous rappelons que la livraison est offerte au-delà de 25 €</p>
    <p style="font-style:italic">
        N’hésitez pas à nous contacter pour plus d’informations sur nos services , événements ou toutes demandes spécifiques.
    </p>
    <div>
        <h3><i class="fas fa-clock"></i>Horaires de livraison</h3>
        <hr>
        <ul>
            <li>Du lundi au vendredi : de <strong>6 h 00</strong> à <strong>11 h 00</strong></li>
            <li>Samedi et Dimanche : de <strong>6 h 00</strong> à <strong>15 h 00</strong></li>
        </ul> 
    </div>
    <div>
        <h3><i class="fas fa-map-marker-alt"></i>Zone de livraison</h3>
        <hr>
        <img src="<?=$router->getWwwPath()."/images/carte1.jpg"?>" alt="carte">
    </div>
    
</div>


