<h2>nouveau produit</h2>
<div class="back">
    <a href="<?=$router->generateUrl('dej_products_show')?>" ><i class="fas fa-undo"></i>Revenir</a>
</div>
<form action="" method="POST" class="container" enctype = "multipart/form-data">
    <div class="row">
        <div class="col-10">
            <label for="name" >Nom :</label>
            <input type="text" name="name" id="name" >
        </div>
        <div class="col-10">
            <label for="description" >Description :</label>
            <textarea  name="description" id="description" rows="4"></textarea>
        </div>
        <div class="col-10">
            <label for="price">Prix :</label>
            <input type="text" name="price" id="price" >
        </div>
        <div class="col-10">
            <label for="img">Choissisez une image :</label>
            <input type="file" name="img" id="img" >
        </div>
        <div class="col-10">
            <label for="category">Catégorie :</label>
            <select name="category" id="category" >
                <option value="boisson_chaude">Boisson chaude</option>
                <option value="jus">Jus</option>
                <option value="viennoiserie">Viennoiserie</option>
                <option value="pain">Pain</option>
            </select>
        </div>
        <div class="col-12 buttonDiv">
            <button class="button1" type="submit">Envoyer</button>
        </div>
    </div>
</form>