<h2>Contactez-nous</h2>
<form method="POST"  class="container">
    <div class="row">
        <div class="col-md-6">
            <label for="name">Nom<span class="etoile"> *</span> :</label>
            <input type="text" id="name" name="name" value ="<?php if(isset($_POST['name'])){ echo $_POST['name'];}?>" placeholder="Votre nom" >
        </div>

        <div class="col-md-6">
            <label for="forname">Prénom<span class="etoile"> *</span> :</label>
            <input type="text" id="forname" name="forname" value ="<?php if(isset($_POST['forname'])){ echo $_POST['forname'];}?>" placeholder="Votre prénom" >
        </div>

        <div class="col-md-6">
            <label for="email">Email<span class="etoile"> *</span> :</label>
            <input type="email" id="email" name="email" value ="<?php if(isset($_POST['email'])){ echo $_POST['email'];}?>" placeholder="Votre e-mail" >
        </div>
        
        <div class="col-md-12">
            <label for="subject">Sujet :</label>
            <input type="text" id="subject" name="subject" value ="<?php if(isset($_POST['subject'])){ echo $_POST['subject'];}?>" placeholder="Votre sujet">
        </div>
        
        <div class="col-md-12">
            <label for="message">Message<span class="etoile"> *</span> :</label>
            <textarea name="message" id="message" placeholder="Votre message" cols="40" rows="10"><?php if(isset($_POST['message'])){ echo $_POST['message'];}?></textarea>
        </div>
        
        <p class="etoile"><strong>* Ces champs sont obligatoires</strong></p>

        <div class="col-md-12">
            <input class="button1 " type="submit" value="Envoyer">
        </div>

        
    </div>  
</form>