<h2>Modifier mon profil</h2>

<form method="Post" class="container" autocomplete="off">
    <div class="row">  
        <div class="col-md-10">
            <label for="name">Nom :</label>
            <input type="text" name="name" id="name" placeholder="Nom" value="<?=$oldInfos['name']?>">
        </div>
        <div class="col-md-10">
            <label for="forname">Prénom :</label>
            <input type="text" name="forname" id="forname" placeholder="Prenom" value="<?=$oldInfos['forname']?>" autocomplete="off">
        </div>
        <div class="col-md-10">
            <label for="email">Email :</label>
            <input type="email" name="email" id="email" placeholder="Email" value="<?=$oldInfos['email']?>" autocomplete="off">
        </div>
        <div class="col-md-10">
            <label for="adress">Adresse :</label>
            <input type="text" name="adress" id="adress" placeholder="Adresse" value="<?=$oldInfos['adress']?>">
        </div>
        <div class="col-md-10">
            <label for="codePostal">Code Postal :</label>
            <input type="text" name="codePostal" id="codePostal" placeholder="Code Postal" value="<?=$oldInfos['codePostal']?>">
        </div>
        <div class="col-md-10">
            <label for="city">Ville :</label>
            <input type="text" name="city" id="city" placeholder="Ville" value="<?=$oldInfos['city']?>">
        </div>
        <div class="col-md-10">
            <label for="phone">Téléphone :</label>
            <input type="tel" name="phone" id="phone" pattern="[0-9]{10}" placeholder="Téléphone" value="<?=$oldInfos['numTel']?>">
        </div>
        <input class="button1" type="submit" value="Envoyer">
    </div>  
</form>