<div class="bigPhoto" id="aboutPhoto">
    <img src="<?=$router->getWwwPath()."/images/aboutUs.jpg"?>" alt="">
    <p class="paraPhoto">De l'idée <span style="text-transform:lowercase">à</span> la création</p>
</div>
<div id="about" class="container">
    <h2>Qui sommes-nous ?</h2>
    <img src="<?=$router->getWwwPath()."/images/141bf4ac578976a7624ce85192472a17.jpg"?>" alt="">
    <p>
        <span>Mon p'tit dej</span> est une start-up de 4 employés , qui d'un constat commun a voulu changer le matin de nombreux français.
        Tout à commencé un matin , avec une envie d'un bon petit déjeuner accompagnée d'une bonne paresse ...<br>
        Apres quelques recherches forcé de constater que ce service n'etait pas disponible ; nous vint l'idée de palier a ce manque.
        Une idée simple qui transformerait chaque matin en un moment de convivialité.
        Quoi de mieux pour commencer la journée qu’un petit-déjeuner tout frais sans sortir de chez soi ?
        <br><span>Mon p'tit dej</span> s'est entouré d’une équipe motivée et impliquée, pour préparer chaque jour des commandes de produits frais et vous livrer efficacement, avec le sourire. Ce sont des hommes et des femmes passionnés qui preparent avant l’aube et sillonnent Paris afin que chacun de nos clients puisse se faire livrer un petit déjeuner choisi et adapté.
        A l’écoute de ses clients, <span>Mon p'tit dej</span> accorde une priorité à la qualité de ses produits et à la relation avec sa clientèle .
        La confiance de nos clients se renouvelle, et nous en sommes fiers.
    </p>
    <div>
        <img src="<?=$router->getWwwPath()."/images/tasse-cafe-chaud-table-bois_1150-10444.jpg"?>" alt="">
        <p>
           Tout a commencé par la livraison de pain,  un matin d'octobre 2018 , qui s'est transformé en livraison de petit dejeuner complet depuis decembre 2019.
           <br> Soucieux de l'environnement, toutes nos livraisons s'effectuent en camionnette 100% electrique  
            <span>Mon ptit dej </span>s'est entouré d’une équipe motivée et impliquée, pour préparer chaque jour des commandes de produits frais et vous livrer efficacement, avec le sourire. <span>Mon petit dej </span>ce sont des hommes et des femmes passionnés qui preparent avant l’aube ou sillonnent les routes parisiennes afin que chacun de nos clients puisse se faire livrer un petit déjeuner choisi et adapté.
            A l’écoute de ses clients, mon petit dej accorde une priorité à la qualité de ses produits et à la relation avec sa clientèle .
            La confiance de nos clients se renouvelle, et nous en sommes fiers.
        </p>
   
    </div>
    
</div>
