<h2>Foire aux questions</h2>
<div id="faq" class="container">
    <div>
        <div class="question">
            <h4><i class="fas fa-plus"></i>Où puis-je me faire livrer ?</h4>
        </div>
        <div  class="hidden answer">
            <p>Nous livrons Paris et ses communes limitrophes.</p>
        </div>
    </div>
    <div>
        <div class="question">
            <h4><i class="fas fa-plus"></i>Comment passer commande ?</h4>
        </div>
        <div class="hidden answer">
            <p>Vous choississez vos formules et valider votre panier ou passer commande par téléphone.</p>
        </div>
    </div>
    <div>
        <div class="question"><h4><i class="fas fa-plus"></i>Quels sont les moyens de paiements acceptés ?</h4></div>
        <div class="hidden">
            <p>Nous acceptons les règlements CB/Paypal.</p>
        </div>
    </div>
    <div>
        <div class="question"><h4><i class="fas fa-plus"></i>J'ai une commande spécifique !</h4></div>
        <div class="hidden">
            <p>Contactez-nous pour nous faire part de vos demandes et envies.</p>
        </div>
    </div>
    <div>
        <div class="question"><h4><i class="fas fa-plus"></i>Jusqu'à quand puis-je passer/modifier/annuler une commande ?</h4></div>
        <div class="hidden">
            <p>Consultez les spécificités dans la rubrique CGV ou contactez-nous via le formulaire.</p>
        </div>
    </div>
    <div>
        <div class="question"><h4><i class="fas fa-plus"></i>Y a t'il un minimum à la commande ?</h4></div>
        <div class="hidden">
            <p>Le montant minimum est de 10 € hors frais de livraison.</p>
        </div>
    </div>
</div>