<div id="partner" class="container-fluid">
    <h2>Nos partenaires</h2>
    <div class="container">
        <div>
            <h3>Nos partenaires, un atout majeur de notre modèle</h3>
            <hr>
            <p>
                La sélection des partenaires est un long processus de découverte et de dégustation (incontestablement la partie la plus agréable de notre métier pour des gourmandes comme nous). Les artisans sont sélectionnés non seulement pour la qualité des produits, mais aussi pour leur approche globale autour de la bonne alimentation.
            </p>
            <p>
                Derrière nos partenaires, ce sont des hommes et des femmes passionnés de leur travail au quotidien, rigoureux et engagés. Toutes ces valeurs que nous partageons chez Baguette à Bicyclette et qui transpirent lors de nos livraisons.
            </p>
            <p>
                Nous favorisons des produits locaux ou à minima français avec toujours pour objectif, votre satisfaction et le bon goût des vrais produits.
            </p>
        </div>
        <div class="row partnerFlex">
            <div class="col-lg-6 img-right" >
                <img src="<?=$router->getWwwPath()."/images/boulangerie.jpg"?>" alt="boulangerie">
            </div>
            <div class="col-lg-6 partnerPara">
                <h4>La boulangerie des rêves</h4>
                <hr>
                <p>
                    Denis Roisil mène à la baguette sa boulangerie bio où tout est fait maison. Et en plus c'est un des premiers boulangers que nous avons référencé. Côté produit, vous ne pourrez pas résister à ses viennoiseries au beurre AOC de Bresse et sa baguette bio.
                </p>
            </div>
        </div>
        <div class="row">
             <div class="col-lg-6 img-left">
                <img src="<?=$router->getWwwPath()."/images/boutique_cafe.jpg"?>" alt="boulangerie">
            </div>
            <div class="col-lg-6 partnerPara">
                <h4>What else ?</h4>
                <hr>
                <p>
                    Denis Roisil mène à la baguette sa boulangerie bio où tout est fait maison. Et en plus c'est un des premiers boulangers que nous avons référencé. Côté produit, vous ne pourrez pas résister à ses viennoiseries au beurre AOC de Bresse et sa baguette bio.
                </p>
            </div>
        </div>
        <div class="row partnerFlex">
            <div class="col-lg-6 img-right" >
                <img src="<?=$router->getWwwPath()."/images/boutique_jus.jpg"?>" alt="boulangerie">
            </div>
            <div class="col-lg-6 partnerPara">
                <h4>Le tout pressé</h4>
                <hr>
                <p>
                    Denis Roisil mène à la baguette sa boulangerie bio où tout est fait maison. Et en plus c'est un des premiers boulangers que nous avons référencé. Côté produit, vous ne pourrez pas résister à ses viennoiseries au beurre AOC de Bresse et sa baguette bio.
                </p>
            </div>
        </div>
    </div>

</div>
